pipeline{
    agent any
    // agent{
    //     label "nodejs"
    // }
    stages{
        // stage("Install dependencies"){
        //     steps{
        //         sh "npm ci"
        //     }
        // }

        // stage("Check Style"){
        //     steps{
        //         sh "npm run lint"
        //     }
        // }

        // stage("Test"){
        //     steps{
        //         sh "npm test"
        //     }
        // }

        // Add the "Deploy" stage here
        stage('Deploy') {
            steps {
                sh '''
                oc project RHT_OCP4_DEV_USER-deploy-strategies
                oc start-build greeting-service --follow --wait
                '''

            }

        }
    }
}
